### ISSUE TITLE
 有没有数据集来比较中文相似度计算的效果？

### ISSUE THREAD

**Issue by hailiang-wang** [yaleimeng/Final_word_Similarity#1]
hi, 我也在做这方面的工作，并且合作了 
https://github.com/huyingxi/Synonyms/

看了您这个工具，咱们可以比较一下。

**Comment by yaleimeng** [comment]
大神您好！
在本项目的参考论文中，第5页提到了其评测方法，第6页给出了一些对比。这里简单引用几句：

>国际上对词语相似度算法的评价标准普遍采用 Miller&Charles 发布的英语词对集的人工判定值 [11 ] 。该词对集由十对高度相关、十对中度相关、十对低度相关共 30 个英语词对组成,然后让 38个受试者对这 30 对进行语义相关度判断，最后取他们的平均值作为人工判定标准 [12 ] 。本文采 用Miller&Charles发布的词对集及其人工判定值作为标准,通过计算各种方法与其的皮尔森相关系数(Pearson correlation coefficient )，将本文提出的方法分别与刘群 [2 ] 和田久乐 [ 10 ] 的方法进行对比。
其参考文献:
[ 11 ]  G A Miller , W G Charles.Contextual correlates ofsemantic similarity [ J ] . Language and CognitiveProcesses , 1991 , 6 ( 1 ): 1 - 28.
[ 12 ]   刘宏哲.文本语义相似度计算方法研究 [ D ] .北京交通大学博士学位论文, 2012.

其将英文词对照翻译过来后，翻译的质量，以此评测相似度计算方法优劣的说服力如何，可能是见仁见智的。另外论文作者团队在该文发表后又有了一些新的工作，进一步提高了该评测方法下的皮尔逊系数。个人精力和技能所限还没有对其实现。

您参与的Synonyms已经受到我的关注，当然了，与传统方法相比，词向量方式的覆盖词汇量更广，优质的词向量对于NLP应用的支持是不可或缺的。崇拜并感谢作者与您的工作！

**Comment by hailiang-wang** [comment]
过奖过奖，谢谢提示。

**Comment by hailiang-wang** [comment]
从你的程序上，得到如下信息：

词林词汇量 32470        知网词汇量 8265
两者总词汇量 40735      重叠词汇量 44986

但是根据网络信息，词林扩展版包含77,343条词语。是不是因为哈尔滨工业大学信息检索实验室并没有开放全部词林词条？
https://baike.baidu.com/item/%E5%90%8C%E4%B9%89%E8%AF%8D%E8%AF%8D%E6%9E%97

**Comment by hailiang-wang** [comment]
做了一个粗略的比较，可以感受一下：https://github.com/huyingxi/Synonyms/issues/33
