### ISSUE TITLE
请问一下，里面有医学领域的词语吗？比如 预防医学、临床医学、医学人文什么的？

### ISSUE THREAD

**Issue by Dinxin** [yaleimeng/Final_word_Similarity#2]

**Comment by yaleimeng** [comment]
感谢您的提问！
词语来源为同义词词林扩展版与hownet2000版。项目中有明文的词条数据可以查看。
如果对其分类体系非常熟悉的话，可以在里面增加专业术语。
如果想尽量规避未登录词问题，当前没有完备的中文知识库可用，只能采用大规模语料训练词向量的方式做近似计算。
另外，类似复合词也可以考虑按短文本对待，采用针对词语序列的相似度计算方案。
希望对您有所帮助！
