### ISSUE TITLE
Is yaleiming(2018) an article?

### ISSUE THREAD

**Issue by karmalet** [yaleimeng/Final_word_Similarity#3]
Hi,

Thanks for wonderful API. I'd like to look into yaleimeng(2018), is it published? where could I get one?

**Comment by yaleimeng** [comment]
No, this project is mostly based on previous work. Maybe the creative work in this project is too small to be published as a paper, I think.  
Code and comments are a good way to understand the algorithm, and references are vrey helpful, too.
If you find something hard to understand, I will add more explanation to the code.
