### ISSUE TITLE
关于RG-65、MC-30和RG-35数据集的下载

### ISSUE THREAD

**Issue by 1204271075** [yaleimeng/Final_word_Similarity#4]
你好，请问你有这三个数据集吗？能发我一份，谢谢！

**Comment by yaleimeng** [comment]
- 翻译后的词语对及人工标注值在相关论文的实验结果部分已有体现。在本项目的example.py中已手工录入，建议认真核对其正确性。
- 如果你想查看英文原版，还请查阅对应的参考文献。
- 后来又发现另几个数百对规模的词语相似性数据集，不过可能主要用于评价和比较词向量训练的效果。

**Comment by 1204271075** [comment]
谢谢，我还以为MC-30和RG-65很大的呢，没想到就这么点单词
