### ISSUE TITLE
库外词

### ISSUE THREAD

**Issue by 18813055625** [yaleimeng/Final_word_Similarity#7]
怎么处理库外词，真的很头痛

**Comment by yaleimeng** [comment]
这种传统方式计算的词语相似度确实有词典覆盖面小的缺点。如果对领域比较熟悉的话，可以按照对应的分类，将词条分配编码，加入到相应的体系中去。
近些年随着词向量的普及，许多人也都用余弦相似度粗略代替了语义相似度了。基于大规模语料的词表覆盖面有很大提高，OOV的情况就变得十分少见了。
