### ISSUE TITLE
请教下：大佬， 如何获取一个词的 所有近意词。

### ISSUE THREAD

**Issue by easywaytodo** [yaleimeng/Final_word_Similarity#8]

**Comment by yaleimeng** [comment]
很抱歉，这个项目没有提供这样的功能。
在同义词词林中，可以查询词出现的所有位置，将对应的一行取出来作为近义词。
hownet中可能要利用词在体系中的位置，寻找同一分支下的作为近义词。

**Comment by easywaytodo** [comment]
我把这个功能做了，要不要提交进去

**Comment by orangefly0214** [comment]
> 我把这个功能做了，要不要提交进去
大佬，请问可以在git上开源一下你做的这个功能吗？

**Comment by yaleimeng** [comment]
@easywaytodo 抱歉没及时看到，欢迎提交Pull Request。
@orangefly0214 希望前面的讨论对你有所提示。因为对于近义词，近到什么程度算近？其实没有明确的标准。需要自己根据对应的知识结构设计方法来筛选。
