### ISSUE TITLE
知网相似度计算问题

### ISSUE THREAD

**Issue by znGitHub** [yaleimeng/Final_word_Similarity#9]
您好，项目首页中知网相似度参考的链接是失效的，请问本项目知网相似度计算使用的是哪篇文献的方法呢？谢谢！

**Comment by yaleimeng** [comment]
很抱歉。可能是原作者删除了他的项目。
不过参考文献方面在hownet目录里面是有的。是刘群等人的论文。
里面那篇新的论文暂未能复现出来。

**Comment by znGitHub** [comment]
> 
> 
> 很抱歉。可能是原作者删除了他的项目。
> 不过参考文献方面在hownet目录里面是有的。是刘群等人的论文。
> 里面那篇新的论文暂未能复现出来。

好的，谢谢。
